Part 5 - Write Up:
1. According to the output I can see that the trend for size of C files as the course progressed increased then peaked in the middle and then decreased
2. The first number is the total sum of all file sizes and the second number is the mean of all file sizes.

Script started on 2022-11-13 15:14:15-08:00 [TERM="xterm-256color" TTY="/dev/pts/133" COLUMNS="212" LINES="67"]
[?2004h[cku2@cancun HW4]$ echo $USER
[?2004l
cku2
[?2004h[cku2@cancun HW4]$ [7mexport PATH=$PATH:.[27mexport PATH=$PATH:.
[?2004l
[?2004h[cku2@cancun HW4]$ echo $PATH
[?2004l
/cse374/hw/HW4:/usr/lib/java/apache-maven-3.8.6/bin:/usr/lib/java/apache-ant-1.10.12/bin:/cse374/hw/HW4:/usr/kerberos/sbin:/usr/kerberos/bin:/usr/lib/java/apache-maven-3.8.6/bin:/usr/lib/java/apache-ant-1.10.12/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/homes/iws/cku2/cse374/hw/HW4:/homes/iws/cku2/.local/bin:/homes/iws/cku2/bin:/homes/iws/cku2/cse374/hw/HW4:.
[?2004h[cku2@cancun HW4]$ wget [7mhttps://courses.cs.washington.edu/courses/cse374/22au/calendar/lecturelist.html[27m
[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Chttps://courses.cs.washington.edu/courses/cse374/22au/calendar/lecturelist.html
[?2004l
--2022-11-13 15:15:05--  https://courses.cs.washington.edu/courses/cse374/22au/calendar/lecturelist.html
Resolving courses.cs.washington.edu (courses.cs.washington.edu)... 128.208.1.193, 2607:4000:200:10::c1
Connecting to courses.cs.washington.edu (courses.cs.washington.edu)|128.208.1.193|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11687 (11K) [text/html]
Saving to: ‘lecturelist.html’


lecturelist.html                                       0%[                                                                                                                       ]       0  --.-KB/s               
lecturelist.html                                     100%[======================================================================================================================>]  11.41K  --.-KB/s    in 0s      

2022-11-13 15:15:05 (139 MB/s) - ‘lecturelist.html’ saved [11687/11687]

[?2004h[cku2@cancun HW4]$ geturls urllist lecturelist.hm[Ktml [K
[?2004l
[?2004h[cku2@cancun HW4]$ data[K[K[K[Krun
runanalysis    runanalysis~   runant.pl      runant.py      runcon         runghc         runghc-8.10.7  rungs          runhaskell     runlevel       run-parts      runtest        runuser        runxlrd
[cku2@cancun HW4]$ runanalysis dataout urllist [K
[?2004l
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/hello.c
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/magic.c
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/printargs.c
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/square1.c
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/control.c
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/control2.c
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/fgets.c
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/argumentdemo.c
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/dangling.c
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/pointeradd.c
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/mystery.c
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/mystery1.c
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/mystery2.c
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/mystery3.c
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/mystery4.c
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/arraydemo.c
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/arraydynamic.c
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/factorial_orig.c
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/factorial_fixed.c
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/reverse_orig.c
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/reverse_fixed.c
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/arrdynamicwrong.c
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/mysterynum.c
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/point.c
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/linkedlist_1.c
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/linkedlist.c
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/linkedlistclient.c
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/debug.c
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/twice.c
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/main.c
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/speak.c
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/shout.c
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/curve.c
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/test.c
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/for.c
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/testfor.c
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/hexdemo.c
...successful
[?2004h[cku2@cancun HW4]$ more ur[K[Kdaa[Kta[K[K[K[Kdaa[Ktaout [K
[?2004l
1 31
2 43
3 51
4 53
5 68
6 72
7 77
8 192
9 106
10 73
11 94
12 46
13 46
14 57
15 41
16 140
17 131
18 63
19 63
20 175
21 190
22 136
23 64
24 247
25 378
26 105
27 51
28 65
29 97
30 38
31 40
32 84
33 50
34 122
35 33
36 73
37 233
[?2004h[cku2@cancun HW4]$ wget [7mhttps://courses.cs.washington.edu/courses/cse374/22au/assignments/scatterplot.R[27m
[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Chttps://courses.cs.washington.edu/courses/cse374/22au/assignments/scatterplot.R
[?2004l
--2022-11-13 15:16:53--  https://courses.cs.washington.edu/courses/cse374/22au/assignments/scatterplot.R
Resolving courses.cs.washington.edu (courses.cs.washington.edu)... 128.208.1.193, 2607:4000:200:10::c1
Connecting to courses.cs.washington.edu (courses.cs.washington.edu)|128.208.1.193|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 417 [text/plain]
Saving to: ‘scatterplot.R’


scatterplot.R                                          0%[                                                                                                                       ]       0  --.-KB/s               
scatterplot.R                                        100%[======================================================================================================================>]     417  --.-KB/s    in 0s      

2022-11-13 15:16:53 (28.1 MB/s) - ‘scatterplot.R’ saved [417/417]

[?2004h[cku2@cancun HW4]$ Rscript scatterplot.R [K
[?2004l
[1] 3628
[1] 98.05405
null device 
          1 
[?2004h[cku2@cancun HW4]$ exit [K
[?2004l
exit

Script done on 2022-11-13 15:17:32-08:00 [COMMAND_EXIT_CODE="0"]
